### ISSUE TITLE
BaseX 8.0: New XQJ Driver

### ISSUE THREAD

**Issue by ChristianGruen** [ligasgr/intellij-xquery#120]
The server protocol in BaseX 8.0 was updated. Could you please update the BaseX XQJ driver to [Version 1.4.0](http://xqj.net/maven/net/xqj/basex-xqj/1.4.0/)? It works with both BaseX 8.0 and older versions. Thanks in advance.

**Comment by CanOfBees** [comment]
Hi ligasgr,

I've tried to [fork and update](https://github.com/CanOfBees/intellij-xquery) the repository to support the new XQJ driver, but I'm afraid that I'm running into problems. 

```
/usr/home/bridger/src/intellij-xquery/src/main/java/org/intellij/xquery/usage/XQueryFindUsageProvider.java:59: cannot find symbol
symbol  : variable FIND_OTHER_USAGES
location: interface com.intellij.find.impl.HelpID
        return HelpID.FIND_OTHER_USAGES;
                     ^
``` 

This error appears to be the main problem when I run the Gradle intellij-xquery [allTests] and [build] commands from IDEA v14.0.3 but that may be a bad assumption on my part.

I'd like to be able to help with this, but I'm afraid that I don't know enough Java to sort through these problems. If you have suggestions or feedback, I'm delighted to try to make additional changes and provide a pull request -- of course, I do realize that it is probably easier for an expert to fix this. 

Thank you for all of your work on the plugin.
Best,
Bridger

**Comment by ligasgr** [comment]
Hi,

@ChristianGruen
Due to some external constraints I'm not able to work on this at the moment. I'll try to sort it out at some point.

@CanOfBees 
from what I can see on your fork you're heading more or less in the right direction :)
The issue is that last release was still built and released with IntelliJ 13 in mind (and on the machine). In order to sort out all the problems that you're facing you either have to be using IntelliJ 13 or do the full migration of the production codebase (some api changes) + lots of debugging and checking IntelliJ source code for fixing all of those failing tests (they did some changes to the internals of the platform which cause some of the tests fail). If you are really determined to know IntelliJ plugin platform from the inside-out - give it a go! Otherwise I'd suggest trying it out on the older version of IDEA.

In general I'll try to sort it out soon (-ish) so if you have the patience please wait for a month or so. If not you can always use the latest driver by configuring your XQuery Data Source (on XQuery Data Sources tab in settings) to use "User defined XQJ driver". This should work fine out of the box!

Thanks and regards,
Grzegorz

**Comment by ChristianGruen** [comment]
Thanks!

**Comment by CanOfBees** [comment]
ligasgr - thank you so much!
